apiVersion: v1
kind: Service
metadata:
  name: mqsterling-ibm-mq-lb
  namespace: mqsterling
  labels:
    app: mqsterling-ibm-mq
    app.kubernetes.io/part-of: mqsterling-ibm-mq
    app-type: mq
spec:
  ports:
    - name: webgui
      port: 9443
      protocol: TCP
      targetPort: 9443
    - name: data
      port: 9157
      protocol: TCP
      targetPort: 9157
    - name: mq
      port: 1414
      protocol: TCP
      targetPort: 1414
  selector:
    app: mqsterling-ibm-mq
  type: LoadBalancer
  externalTrafficPolicy: Cluster

