kind: PersistentVolume
apiVersion: v1
metadata:
  name: resources
  labels:
    intent: resources
spec:
  storageClassName: "ibmc-file-gold"
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 100Mi
  nfs:
    server: fsf-dal1003h-fz.adn.networklayer.com
    path: /IBM02SEV1594147_5/data01/resources

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: logs
  labels:
    intent: logs
spec:
  storageClassName: "ibmc-file-gold"
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 500Mi
  nfs:
    server: fsf-dal1003h-fz.adn.networklayer.com
    path: /IBM02SEV1594147_5/data01/logs

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: documents
  labels:
    intent: documents
spec:
  storageClassName: "ibmc-file-gold"
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 500Mi
  nfs:
    server: fsf-dal1003h-fz.adn.networklayer.com
    path: /IBM02SEV1594147_5/data01/documents
